// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Garage struct {
	Carid           string  `json:"carid"`
	DateOfManufac   *string `json:"DateOfManufac,omitempty"`
	LastServiceDate *string `json:"LastServiceDate,omitempty"`
	UniqueID        *string `json:"UniqueID,omitempty"`
	LastUsedDate    *string `json:"LastUsedDate,omitempty"`
	Available       *bool   `json:"Available,omitempty"`
}

type GetCar struct {
	Carid  string `json:"carid"`
	Userid string `json:"userid"`
}

type Login struct {
	Phno     string `json:"phno"`
	Password string `json:"password"`
}

type Signup struct {
	Fname    *string `json:"fname,omitempty"`
	Lname    *string `json:"lname,omitempty"`
	Phno     string  `json:"phno"`
	Password string  `json:"password"`
}

type User struct {
	Userid   *string `json:"userid,omitempty"`
	Fname    *string `json:"fname,omitempty"`
	Lname    *string `json:"lname,omitempty"`
	Phno     *string `json:"phno,omitempty"`
	Password *string `json:"password,omitempty"`
	Carid    *string `json:"carid,omitempty"`
}
