// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AuthResponse struct {
	AuthToken *AuthToken `json:"authToken"`
	User      *User      `json:"user"`
}

type AuthToken struct {
	AccessToken string    `json:"accessToken"`
	ExpiredAt   time.Time `json:"expiredAt"`
}

type Garage struct {
	Carid           string  `json:"carid"`
	DateOfManufac   *string `json:"DateOfManufac,omitempty"`
	LastServiceDate *string `json:"LastServiceDate,omitempty"`
	UniqueID        *string `json:"UniqueID,omitempty"`
	LastUsedDate    *string `json:"LastUsedDate,omitempty"`
	Available       *bool   `json:"Available,omitempty"`
}

type GetCar struct {
	Carid  string `json:"carid"`
	Userid string `json:"userid"`
}

type Login struct {
	Phno     string `json:"phno"`
	Password string `json:"password"`
}

type Signup struct {
	Userid   string  `json:"userid"`
	Fname    *string `json:"fname,omitempty"`
	Lname    *string `json:"lname,omitempty"`
	Phno     string  `json:"phno"`
	Password string  `json:"password"`
}

type User struct {
	Userid   string  `json:"userid"`
	Fname    *string `json:"fname,omitempty"`
	Lname    *string `json:"lname,omitempty"`
	Phno     string  `json:"phno"`
	Password string  `json:"password"`
}
