// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import "time"

type AuthResponse struct {
	AuthToken *AuthToken `json:"authToken"`
	User      *User      `json:"user"`
}

type AuthToken struct {
	AccessToken string    `json:"accessToken"`
	ExpiredAt   time.Time `json:"expiredAt"`
}

type Login struct{
	UserID string `json:"userid"`
	Password string `json:"password"`
}

type Signup struct{
	UserID string `json:"userid"`
	Fname string `json:"fname"`
	Lname string `json:"lname"`
	Password string `json:"password"`
}

type GetCar struct{
	CarID string `json:"carid"`
	UserID string `json:"userid"`
}

